Black-Scholes-Merton index level at maturity

$S_T = S_0 exp ((r - \frac{1}{2} \sigma^2)T + \sigma \sqrt{T} z)$

Monte Carlo estimator for European option

$C_0 \approx e^{-rT}\frac{1}{I}\sum h_T(i)$


In [1]:
#
# Monte Carlo valuation of European call option
# in Black-Scholes-Merton model
# bsm_mcs_euro.py
#
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


In [2]:
# Parameter values
S0 = 100.       # initial index level
K = 105.        # strik price
T = 1.0         # time-to-maturity
r = 0.05        # riskless short rate
sigma = 0.2     # volatility

I = 1000000      # number of simulations

In [3]:
# Valuation Algorithm
z = np.random.standard_normal(I)    #pseudorandom numbers
ST = S0 * np.exp((r - 0.5 * sigma ** 2) * T + sigma * np.sqrt(T) * z)
    # index values at maturity
hT = np.maximum(ST - K, 0)  # inner values at maturity
C0 = np.exp(-r * T) * np.sum(hT) / I # Monte Carlo estimator

In [4]:
# Result Output
print("Value of the European Call Option %5.3f" % C0)

Value of the European Call Option 8.031


In [5]:
print(len(z))
z

1000000


array([ 0.04582045, -0.81483541, -0.01589862, ..., -0.0425619 ,
        2.02018426, -0.99965911])

In [6]:
print(len(ST))
ST

1000000


array([103.99411145,  87.54939103, 102.71831765, ..., 102.17201413,
       154.3475746 ,  84.37223381])

In [7]:
ST - K

array([ -1.00588855, -17.45060897,  -2.28168235, ...,  -2.82798587,
        49.3475746 , -20.62776619])